import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../../config/theme.dart';

/// Shared live implementation for the supplied quotation, documents and
/// provider-request designs. It deliberately has no seeded cards.
class LiveTradeOperationsScreen extends StatelessWidget {
  const LiveTradeOperationsScreen({super.key, required this.mode});
  final String mode;
  String get title => switch (mode) {'quotes' => 'Quotations', 'documents' => 'Trade documents', 'providers' => 'Logistics requests', _ => 'Trade operations'};
  String get collection => switch (mode) {'quotes' => 'offers', 'providers' => 'service_requests', _ => 'orders'};
  @override Widget build(BuildContext context) {
    final user = FirebaseAuth.instance.currentUser;
    return Scaffold(backgroundColor: Colors.white, appBar: AppBar(title: Text('AfriGoOS • $title'), actions: [IconButton(onPressed: () => context.push('/notifications'), icon: const Icon(Icons.notifications_none_rounded))]), body: user == null ? const _State(icon: Icons.lock_outline, title: 'Sign in required', text: 'Sign in to view authorised trade activity.') : StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream: FirebaseFirestore.instance.collection(collection).where('participantIds', arrayContains: user.uid).snapshots(), builder: (context, snapshot) { if (snapshot.hasError) return const _State(icon: Icons.cloud_off_outlined, title: 'Live data unavailable', text: 'Check your connection and try again.'); if (!snapshot.hasData) return const Center(child: CircularProgressIndicator()); final records = snapshot.data!.docs; return ListView(padding: const EdgeInsets.fromLTRB(20,20,20,32), children: [Text(title, style: AfrigoTypography.soraHeading2.copyWith(color: AfrigoColors.textPrimary)), const SizedBox(height: 6), Text(_intro(), style: AfrigoTypography.interBody1.copyWith(color: AfrigoColors.textSecondary)), const SizedBox(height: 20), if (records.isEmpty) _State(icon: _icon(), title: _emptyTitle(), text: _emptyText()) else ...records.map((doc) => _Card(mode: mode, id: doc.id, data: doc.data())), if (mode == 'providers') Padding(padding: const EdgeInsets.only(top: 16), child: Text('Provider rates and availability are confirmed only after a vetted provider responds.', style: AfrigoTypography.interBody2.copyWith(color: AfrigoColors.textSecondary))) ]); }));
  }
  IconData _icon() => switch(mode) {'quotes' => Icons.request_quote_outlined, 'documents' => Icons.folder_open_outlined, _ => Icons.local_shipping_outlined};
  String _intro() => switch(mode) {'quotes' => 'Review real offers and negotiate terms before accepting.', 'documents' => 'Documents are private to authorised trade participants.', _ => 'Requests are sent only to approved logistics providers.'};
  String _emptyTitle() => switch(mode) {'quotes' => 'No quotations yet', 'documents' => 'No trade documents yet', _ => 'No logistics requests yet'};
  String _emptyText() => switch(mode) {'quotes' => 'Submitted supplier offers will appear here automatically.', 'documents' => 'Documents appear when an authorised participant uploads them to a trade case.', _ => 'Open a trade case and request logistics when your shipment details are ready.'};
}
class _Card extends StatelessWidget { const _Card({required this.mode, required this.id, required this.data}); final String mode,id; final Map<String,dynamic> data; String _value(List<String> keys,String empty){for(final k in keys){final v=data[k];if(v!=null&&v.toString().trim().isNotEmpty)return v.toString();}return empty;} @override Widget build(BuildContext context) { final status=_value(['status','stage'],'pending').replaceAll('_',' '); final title=_value(['productName','commodity','title','cargo'],mode=='quotes'?'Quotation':mode=='documents'?'Trade record':'Logistics request'); return AnimatedContainer(duration: const Duration(milliseconds:180), margin: const EdgeInsets.only(bottom:12), padding: const EdgeInsets.all(16), decoration: BoxDecoration(color: const Color(0xFFF5FAF7),borderRadius:BorderRadius.circular(18),border:Border.all(color:AfrigoColors.borderLight)), child: InkWell(onTap: () => context.push(mode == 'providers' ? '/orders/${_value(['orderId'],'')}/logistics' : '/orders/detail/${_value(['orderId','orderID'],id)}'), child: Row(children:[Icon(mode=='quotes'?Icons.request_quote_outlined:mode=='documents'?Icons.description_outlined:Icons.local_shipping_outlined,color:AfrigoColors.primary),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:AfrigoTypography.interBody2Semi),const SizedBox(height:3),Text(status,style:AfrigoTypography.interBody3.copyWith(color:AfrigoColors.textSecondary))])),const Icon(Icons.chevron_right_rounded)])));}}
class _State extends StatelessWidget { const _State({required this.icon,required this.title,required this.text}); final IconData icon;final String title,text; @override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.symmetric(vertical:64,horizontal:20),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(icon,size:52,color:AfrigoColors.primary),const SizedBox(height:14),Text(title,style:AfrigoTypography.soraHeading5),const SizedBox(height:8),Text(text,textAlign:TextAlign.center,style:AfrigoTypography.interBody2.copyWith(color:AfrigoColors.textSecondary))]));}
