import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../config/theme.dart';
import '../../providers/auth_provider.dart';

/// Replacement for the supplied business-settings screen. Every row leads to
/// an available account surface; access administration is intentionally
/// marked unavailable until server-side organisation membership is enabled.
class BusinessSettingsScreen extends ConsumerWidget {
  const BusinessSettingsScreen({super.key});
  @override Widget build(BuildContext context, WidgetRef ref) { final user=ref.watch(currentUserProvider); final name=(user?.fullName.trim().isNotEmpty??false)?user!.fullName:'Your business'; return Scaffold(backgroundColor:Colors.white,appBar:AppBar(backgroundColor:Colors.white,surfaceTintColor:Colors.white,title:const Text('AfriGoOS'),actions:[IconButton(onPressed:()=>context.push('/notifications'),icon:const Icon(Icons.notifications_none_rounded))]),body:ListView(padding:const EdgeInsets.fromLTRB(20,20,20,32),children:[Text('Business settings',style:AfrigoTypography.soraHeading2),const SizedBox(height:6),Text(name,style:AfrigoTypography.interBody1.copyWith(color:AfrigoColors.textSecondary)),const SizedBox(height:22),Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:const Color(0xFFF0F8F3),borderRadius:BorderRadius.circular(18)),child:Row(children:[const CircleAvatar(radius:32,backgroundColor:Color(0xFFD7EFDF),child:Icon(Icons.business_outlined,size:32,color:AfrigoColors.primary)),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(name,style:AfrigoTypography.soraHeading5),Text('Authenticated business account',style:AfrigoTypography.interBody2.copyWith(color:AfrigoColors.textSecondary))]))])),const SizedBox(height:18),_row(context,Icons.business_outlined,'Business profile','Company details, address and contact','/profile/edit'),_row(context,Icons.groups_outlined,'Team & permissions','Managed by AfriGoOS business administration','/team'),_row(context,Icons.notifications_outlined,'Notification preferences','Trade updates, messages and alerts','/settings'),_row(context,Icons.language_outlined,'Language','English','/settings'),_row(context,Icons.shield_outlined,'Security & sign-in','Password and account security','/settings'),_row(context,Icons.credit_card_outlined,'Subscription & billing','Plan, payments and invoices','/payments'),const SizedBox(height:14),OutlinedButton.icon(onPressed:()=>ref.read(authProvider.notifier).logout(),style:OutlinedButton.styleFrom(foregroundColor:Colors.red,side:const BorderSide(color:Colors.red),minimumSize:const Size.fromHeight(54)),icon:const Icon(Icons.logout),label:const Text('Sign out'))])); }
  Widget _row(BuildContext context,IconData icon,String title,String sub,String route)=>Padding(padding:const EdgeInsets.only(bottom:10),child:Card(elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(15),side:const BorderSide(color:AfrigoColors.borderLight)),child:ListTile(onTap:()=>context.push(route),contentPadding:const EdgeInsets.symmetric(horizontal:16,vertical:8),leading:CircleAvatar(backgroundColor:const Color(0xFFEEF7F1),child:Icon(icon,color:AfrigoColors.primary)),title:Text(title,style:AfrigoTypography.interBody2Semi),subtitle:Text(sub),trailing:const Icon(Icons.chevron_right_rounded))));
}
